### ISSUE TITLE
Make the State selector autocomplete

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#107]
Users should be able to start typing a state and see the options update or scroll through and select a state.

**Comment by 09Kathy** [comment]
How it is now (in dev), Event State is single-select and the state filter is multi-select. Do we want to keep it that way or have both of them be multi or single?

**Comment by lprivette** [comment]
As is. Filters for the Event list drop down should be single select. 

Main filter state one should be multiple select
