### ISSUE TITLE
Setup Login 

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#114]
Users should be prompted to login with their STN username and password before being able to interact with the app.

We'll need to store their username, password, and role in local storage.

**Comment by BlakeDraper** [comment]
@lprivette Just to confirm - you do envision this as a whole page login, where the user is directed to (or redirected) if not logged in - like the current STNweb. As opposed to a click to login in a modal, which allows the user to see/interact with the app in a non-authenticated mode (like WHISPers).
