### ISSUE TITLE
Skip sites that are clearly out of place

### ISSUE THREAD

**Issue by 09Kathy** [USGS-WiM/stnweb2#147]
There are 3 main sites that look like errors if user is panning around the full map:
![image](https://user-images.githubusercontent.com/46943254/102656941-61398400-413a-11eb-8e1e-fd2631021292.png)
![image](https://user-images.githubusercontent.com/46943254/102656986-74e4ea80-413a-11eb-89e2-dfc304fb5960.png)
^(there aren't islands there)

**Comment by 09Kathy** [comment]
also skipping TXNEW22417 while I'm at it because description is: "Site ACCIDENTALLY CREATED, UNABLE TO DELETE. NO DATA TO REPORT."

**Comment by lprivette** [comment]
hol up. I'll delete that one from DB
