### ISSUE TITLE
Add an option for 'All' under HWMS Surveyed filter

### ISSUE THREAD

**Issue by 09Kathy** [USGS-WiM/stnweb2#149]
As it is now, once you select one you're stuck with one or the other:
![image](https://user-images.githubusercontent.com/46943254/102661581-b8dbed80-4142-11eb-9c53-6c2b063f707c.png)

**Comment by lprivette** [comment]
User should only be able to select one of those options. There should be an ability to clear them though

**Comment by lprivette** [comment]
oh sorry that's what you're saying right?

**Comment by 09Kathy** [comment]
yeah! I don't know the exact solution. Was thinking adding an 'All' radio button but maybe 'Either' or 'No Filter' or something works too

**Comment by lprivette** [comment]
I'll check to see if it's a required field when submitting a HWM. I wonder if that component allow you to click again to unselect. so in the image above click "Unsurveyed" would deselect it.

**Comment by 09Kathy** [comment]
oh, ok. How it works now, 'Unsurveyed' returns all the sites not listed as surveyed. We could have a think that says 'Would you like to filter out unsurveyed sites and select 'Yes' or 'No' - yes returns surveyed and no returns all of them

**Comment by lprivette** [comment]
surveyedHWMs: "true for sites with surveyed hwms only, false for those with unsurveyed hwms"

So it's different, selecting "Surveyed" will return sites with hwms that have a `surveyed_date` populated. "Unsurveyed" would return sites with no `surveyed_date`. And unselected would return all sites.

**Comment by 09Kathy** [comment]
Since radio buttons don't have an option to unselect,, should we just circle back to an 'All' radio button? Or add a little 'clear' button or something else?

**Comment by lprivette** [comment]
I'd like to keep the form uniform in the sense that if something isn't contributing to the filter results, then it's not selected/has no input. We could add the All and have it selected by default, but it would be the only filter like that. Not a huge deal, but doesn't feel consistent.

**Comment by lprivette** [comment]
but yes it's a problem as is. what about switch to toggles? they can be toggled on/off, but if one is checked and the user tries to check the other then it switches off the first one.

**Comment by 09Kathy** [comment]
oh, I like the toggle idea!

**Comment by lprivette** [comment]
both should be off by default
