### ISSUE TITLE
Unable to filter by one state 

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#190]
The search satisfies the requirements stated by the toast

![image](https://user-images.githubusercontent.com/23640741/106315966-05364500-623a-11eb-9aa6-83304af22a11.png)

**Comment by 09Kathy** [comment]
'Event State' only impacts the event list. The 'States' filter below filters the sites by state. Maybe we should include some sort of explanation at the top about what event type and event state filters do.
