### ISSUE TITLE
Move Map Filters into a Sidebar with collapsible sections

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#199]
Current implementation is confusing to users and looks bad. I don't know what I was thinking. Good thing we're in Pre-Alpha.

Whispers has a really nice implementation of this (image below). Ours will be less complex.
![image](https://user-images.githubusercontent.com/23640741/115452889-fdf55680-a1ec-11eb-8300-e1873f5bbfca.png)

- [ ] create sidebar component
- [ ] situate sidebar component on left side of page; to the left of the map
- [ ] move map filters into new side bar, see image below for placement. Up for input on this. I mainly just want to ensure the filters that effect the Event List are obvious. Might even be better to just include them within the "Events" panel instead of the way I have it in that mock up.

![image](https://user-images.githubusercontent.com/23640741/115460306-1b7aee00-a1f6-11eb-844d-69ea51d28eae.png)

**Comment by Abigail770** [comment]
@lprivette it looks like there is a filter component that already exists but is empty apart from some css.  Would you like me to put the map filters in that component or create a new component for them?

**Comment by lprivette** [comment]
Yes, I suggest using that `filter` component. And remove any unused or duplicated css in that `filter.component.scss` file. Looks like some css in that file and the `map.component.scss` are identical

**Comment by Abigail770** [comment]
Okay, sounds good.  Thanks!

**Comment by Abigail770** [comment]
@lprivette should the event list filters also be cleared when the Clear Filters button is clicked?  It looks like they are not currently (the value the user sees is cleared, but the Event List doesn't change accordingly).  I could add that in if you want, or maybe that would be a separate issue.

**Comment by lprivette** [comment]
Ah yes good bug catch! Please create a separate issue for that, and add it to the project board (https://github.com/orgs/USGS-WiM/projects/4#card-59477976)

Random pro-tip moment: When reporting bugs, it's extremely helpful to include Steps to Reproduce the issue. It can help avoid situations where a user is reporting something, but you can't recreate it, so you end up going back a forth and wasting time. This is more important when working with cooperators who aren't familiar with development work.

here's what it'd look like for this bug:

**Steps to Reproduce**:
1. Filter events by Type: Noreaster
2. Confirm that Event list is only showing Noreasters
3. Click the "Clear Filters" button
4. Click the Event list, start typing, and note that only Noreasters are still present

**Expected Behavior**:
Event list should display all events after hitting the "Clear Filters" button

**Comment by Abigail770** [comment]
@lprivette how would you like the sidebar filters to be displayed on mobile screen sizes?  Should they be displayed below the map?

**Comment by lprivette** [comment]
Hmm. It'd be nice if we could get them into a toggleable button once it's mobile sized, just like the leaflet layer control currently on the map, but it may look weird with so many filters.

Or we could put the filters above the map. Then the table isn't too buried. So the order would be Filters, Map, Table results. But that could be kinda confusing for the users if the map is offscreen due to the filters. so maybe directly below the map would be best.

What do you think about those other placement ideas?

**Comment by Abigail770** [comment]
I agree, it might be more obvious that the map needs to be filtered if the filters are above the map. 

I like the idea of putting them in a button on a mobile size too - something like a button above the map, where if the button is clicked the filters expanded to completely cover the map on the screen, sort of like a separate page.  Just an idea though, I'm not sure how that would look or how difficult that would be to implement!

**Comment by lprivette** [comment]
Want to give that a shot? Mitch on the team is really good at mobile/css stuff in general, so if you do get stuck you could post in fresh eyes or message him
