### ISSUE TITLE
Add streamgage layer

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#200]
Athena has requested that we add the streamgage layer to stnweb.

Let's see if we can use the `markercluster` library to display them so that we don't have to restrict display on zoom.

We are already using that plugin with the STN All Sites layer

**Comment by HansVraga** [comment]
Do we have a mapservice for streamgages?

**Comment by lprivette** [comment]
pretty sure she's talking about the nwis real time streamgages like we have in FEV. I will double check

**Comment by HansVraga** [comment]
Right - we're not hitting a map service for that, right? I'm wondering if we need to be concerned about dealing with a large response for higher zoom levels.

**Comment by Abigail770** [comment]
From the REST service test page, it looks like there is a 25 degree limit on the bounding box: 
![image](https://user-images.githubusercontent.com/54085652/123996561-132cf500-d995-11eb-8f51-b592c8060c30.png)
Should we limit the visible zoom level (and if so, continue to use the markerCluster library, or load all markers?)?

**Comment by lprivette** [comment]
oh interesting I had no idea! I suppose we can follow the same method we're doing in other apps, so yes limit the visible zoom and just load all the markers. Bummer tho. I love that markerCluster package lol

**Comment by Abigail770** [comment]
@lprivette the hamburger menu in the popup and the Loading Layers wheel in FEV use Font Awesome.  Should I add Font Awesome in or use different icons (like Angular Material icons)?

**Comment by lprivette** [comment]
Use the Angular Material icons, thanks for checking!
