### ISSUE TITLE
Add "NOAA Tides and Currents Stations" layer

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#201]
This layer is already in FEV https://stn.wim.usgs.gov/fev/#2020HurricaneDelta

- [x] title layer "NOAA Tides and Currents Stations"
- [x] Use same icon that is used in DOI FEV (`wmm-diamond wmm-lime wmm-icon-triangle wmm-icon-black wmm-size-15 wmm-borderless`)
- [ ] Add popup up that links to hydrograph on NOAA site (same as it does in FEV)

**Comment by Abigail770** [comment]
@lprivette should the date range for the link in the popup change according to the event selected (e.g. Hurricane Delta 2020), but stay the same for all other filters used (like Network, Sensor)?

**Comment by lprivette** [comment]
Good question! 

Similarly to how it is done in FEV (see https://github.com/USGS-WiM/FEV/blob/965bbaca341fe0be7dc4907c99a6a9a42d791e8f/src/scripts/query.js#L643), If an event is selected, then use the event's start and end dates for the noaa url. 

If no event is selected, then how about we just use the past 2 weeks?
