### ISSUE TITLE
Turn on hourly back ups for Hurricane Henri

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#222]

**Comment by lprivette** [comment]
Users will start entering data today

**Comment by aaronstephenson** [comment]
I just enabled it. (Sorry, I was out on Annual Leave all last week.)

I _think_ you have permissions to do this too. When you return from your leave, take a look and let me know.

**Comment by lprivette** [comment]
I would be editing a file in s3 in the "WIM Lambda" folder?

**Comment by aaronstephenson** [comment]
It's a toggle on the CloudWatch cron (tho they recently changed the name to EventBridge) that's attached to the Lambda function. The way I do it is:

1. Navigate to the Lambda -> Functions -> STNRDSBackupsHourly
2. Click the Configuration tab in the row of tabs in the middle of the screen
3. Click Triggers
4. Click the link to the EventBridge resource (it has the same name as the Lambda function, STNRDSBackupsHourly)
5. Click the Edit button at the top right
6. Scroll down until you reach the Select event bus section
7. Click the "Enable the rule on the selected event bus" toggle
8. Click the Update button at the bottom of the page

Alternately it would be slightly quicker to just go to EventBridge first
1. Navigate to EventBridge -> Events -> Rules
2. Click on the STNRDSBackupsHourly rule
3.  Click the Edit button at the top right
4. Scroll down until you reach the Select event bus section
5. Click the "Enable the rule on the selected event bus" toggle
6. Click the Update button at the bottom of the page

Let me know if you aren't able to access and edit these.

**Comment by aaronstephenson** [comment]
@lprivette can this be shut off now?
