### ISSUE TITLE
Create Site Pages

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#226]
- [x] utilize this existing 'site-details' component
- [x] clicking siteid in popup will navigate to this page
- [x] when navigating to a site page the url should be 'Site/27067/SiteDashboard'

First interation of design (will be discussed at next checkin):
![image](https://user-images.githubusercontent.com/23640741/137644799-cafaea5f-7b81-42a5-92ca-56dcfb2fa4f8.png)

**Comment by Abigail770** [comment]
A couple questions:
1. Do we want each section to be collapsible using the section header?
2. I think we discussed linking the site detail page elsewhere (potentially in a toolbar at the top) instead of linking from the popup.  Or do we want both?

**Comment by lprivette** [comment]
1. yes
2. it will be both, but we'll need to discuss what clicking on "Sites" in the navbar would do. In current stnweb it opens up a search and then takes you to the site you enter. You also have some filter opitions. I would want to see what functionality is actually being used on that sites page (apart from the direct search) before fully implementing the whole thing. See current stn webs site page below. 

![image](https://user-images.githubusercontent.com/23640741/137957400-6284c7a9-9280-44aa-a407-2cbef75d646c.png)

For now if you want to work directly on the site-details page, i'd just set up navigation to through the popup and we'll setup the Site page in the navbar after more discussion.

**Comment by Abigail770** [comment]
I want to make sure I'm using the correct object returned from the services for each site field.  There are a few that aren't clear to me or that just have an id returned (e.g. hortizontal datum id), which I would guess need to be cross-referenced with another key somewhere.  I also want to make sure I'm using the right services to get site details.

The bolded fields are ones that need clarification:

### **From Single Site (https://stn.wim.usgs.gov/STNServices/Documentation/Site/ASite):**
Site Description: site_description
**Created By - ??? (member_id?)**
Waterbody: waterbody
Drainage Area – drainage_area_sqmi
Station ID (USGS): usgs_sid
Station ID (NOAA): noaa_sid
Station ID (Other): other_sid
Address: address
City: city
State: state
County: county
Zip: zip
Latitude: latitude_dd (currently rounding to 2 decimal places)
Longitude: longitude_dd (currently rounding this to 2 decimal places)
**Horizontal Datum: hdatum_id (needs to be cross-referenced?)
Collection Method: hcollect_method_id (needs to be cross-referenced?)**
Network Type: network_type_site
Network: network_name_site
Zone: zone
**Sensor Permissions: ??? (sensor_not_appropriate?)**
Permanent Housing – is_permanent_housing_installed
**Land Owner Contact: landownercontact_id (needs to be cross-referenced?)**
Safety Notes: safety_notes
**Internal Notes: site_notes
Permission Granted: access_granted**

### **Housing (https://stn.wim.usgs.gov/STNServices/Documentation/SiteHousing/SiteSiteHousings):**
**Housing Type: housing_type_id (needs to be cross-referenced?)**
Housing Length: length
Housing Material: material
Amount: amount
Notes: notes

**Comment by lprivette** [comment]
The endpoint for sites is that one https://stn.wim.usgs.gov/STNServices/Sites/{{number}}.json. So to create a site it'd be a POST at https://stn.wim.usgs.gov/STNServices/Sites.json. (but we're just focusing on displaying the existing data right now)

Created by would be `member_id`.

horizontal datum lookup: https://stn.wim.usgs.gov/STNServices/HorizontalDatums.json
collection method: https://stn.wim.usgs.gov/STNServices/HorizontalMethods.json

I think "Sensor Permissions" is supposed to be "Sensor Permanent"? or do you have any clarification on what that field equates to in old stnweb @chaqazarad If it is supposed to reference it's permanence then it'd be the `is_permanent_housing_installed` field

landowner POST would be https://stn.wim.usgs.gov/STNServices/LandOwners.json and to get a landowner would be https://stn.wim.usgs.gov/STNServices/Sites/28053/LandOwner.json

Internal notes is correct with `site_notes`

Site Housing is another lookup and would need to be queried: https://stn.wim.usgs.gov/STNServices/SiteHousings.json (POST) so to get them for a site https://stn.wim.usgs.gov/STNServices/sites/31776/SiteHousings.json for example

Permission granted is correct with `access_granted`

let me know if I've missed anything or added to your confusion Abby! These services are A LOT.  I'm also going to dm you with some old STNWeb creds. I think it will be helpful for you to look at the old form with the network tab open and see what requests are getting fired off as you mess with a site page.

**Comment by Abigail770** [comment]
Thanks! That all makes sense.  I was able to get all of those lookups to work except the landowner contact.  Do I need some sort of extra permissions for that?  When I go to the links for landowner you sent, I'm getting a 401 Unauthorized error:
![image](https://user-images.githubusercontent.com/54085652/138310650-96f1bfba-6a6d-4daa-94f1-094742a10e4d.png)

**Comment by Abigail770** [comment]
@lprivette there are a few fields in the dialogs I haven't been able to find data for in the endpoints.  Do you know which endpoints these would be associated with?

**Sensor dialog:**
- Tapedowns
- Elevations (sensor, ground, wse)
- -In feet above
- Preview time in UTC (not sure if this is from an endpoint or just convert the time zone to UTC if it's in a different time zone)

**Files (photo)**
- Source Photographer
- Photo lat
- Photo lon
- Photo date/date uploaded (there is a file_date field, so not sure which this would be, and then where the other date would come from)
- Preview caption

**Files (non-photo)**
- Source name (not sure where to get the member id associated with a file)
- Approval info

**Comment by lprivette** [comment]
**Sensor dialog:**
- **Tapedowns** 
     - Corresponds with OPMeasurements, 
     -  example: https://stn.wim.usgs.gov/STNServices/InstrumentStatus/18564/OPMeasurements
     -  https://stn.wim.usgs.gov/STNServices/Documentation/OPMeasurement/AllOPMeasurement
     -  site with sensor tapedown: https://stn.wim.usgs.gov/stnweb/#/Site/31777/SiteDashboard
- **Elevations (sensor, ground, wse)**
     - Is a part of the Instrument Status enpdoint
     - example: https://stn.wim.usgs.gov/STNServices/InstrumentStatus/18564.json
     - https://stn.wim.usgs.gov/STNServices/Documentation/SensorStatus/AllSensorStatuses
- **In feet above**
     - This should correspond with the vertical datums endpoint https://stn.wim.usgs.gov/STNServices/Documentation/VerticalDatum/AllVerticalDatums
     - So https://stn.wim.usgs.gov/STNServices/Sites/31777/ObjectivePoints.json has that `vdatum_id` which corresponds to the id that vertical datum lookup
     - Are you seeing that working anywhere in the old client? It actually seems broken to me.
- **Preview time in UTC (not sure if this is from an endpoint or just convert the time zone to UTC if it's in a different time zone)**
     - This conversion is happening in the client code unfortunately. It's using moment.js which is considered to be in maintenance mode now https://momentjs.com/docs/#/-project-status/, so we probably won't want to use moment here. Looks like they have suggestions on newer packages https://momentjs.com/docs/#/-project-status/recommendations/

**Files (photo)**
- Source Photographer
     - `source_id` https://stn.wim.usgs.gov/STNServices/Sources/410.json 
     - it looks like that `source_id` field is present on many of the file endpoints https://stn.wim.usgs.gov/STNServices/Documentation/File/SiteFiles
- Photo lat
- Photo lon
     - examples: https://stn.wim.usgs.gov/STNServices/Sites/4285/Files.json OR https://stn.wim.usgs.gov/STNServices/Files/11081.json
     - note that the `latitude_dd` and `longitude_dd` only show up on the object if they have them. If those fields don't have values they won't show up on the response for that entry.
- Photo date/date uploaded (there is a file_date field, so not sure which this would be, and then where the other date would come from)
     - Like the lat/long, the "Photo Date" field will only show up in the response if it has a value
     - example: https://stn.wim.usgs.gov/STNServices/Sites/4285/Files.json there is a file here that has a `photo_date` field
     - So `file_date` is the date uploaded. And `photo_date` is an optional date for when the photo was actually taken.
- Preview caption
     - created and displayed in the client, not stored in the db 

**Files (non-photo)**
- Source name (not sure where to get the member id associated with a file)
- Approval info

**Comment by Abigail770** [comment]
Is the elevation for tapedowns coming from the vdatum from the instrument status? I don't see a vdatum or vdatum_id as part of the OP Measurement endpoint and at least for the sites with tapedowns I'm looking at, it looks like the same value as In Feet Above. Or are those different?

**Comment by lprivette** [comment]
This is what I'm seeing when I look at current stnweb
![image](https://user-images.githubusercontent.com/23640741/140084509-49fffe41-89d8-4389-928f-4fca33bfb9e6.png)
and that's the the OPMeasurements. So that tapedown section that is linked to the "Datum Location" or OP is associated with the Measurements 

And then the section below that is associated with the instrument status
https://stn.wim.usgs.gov/STNServices/InstrumentStatus/18136.json
![image](https://user-images.githubusercontent.com/23640741/140085200-286804ed-9581-4b73-ae36-2bcaebfb0ea4.png)

Ok yeah so InstrumentStatus has the vdatum_id and yes that would be the same as the 'In Feet Above'. I can't even find a working example of the In Feet Above having a value in the client. like it's always blank despite showing up when I 'edit' 

Might be easier to explore this over a call. let me know if you want to do that, my schedule is super open today

**Comment by Abigail770** [comment]
- Date processed/Collected
     - 
- Data Process By
- Preview Caption
     - created and displayed in the client, not stored in the db

**Comment by lprivette** [comment]
- Date processed/Collected
     -  Would be `collect_date` on the datafile endpoint  (e.g. https://stn.wim.usgs.gov/STNServices/DataFiles/3947.json)
- Data Process By
     - corresponds with the `processor_id` field on the datafile endpoint (e.g. https://stn.wim.usgs.gov/STNServices/DataFiles/3947.json) which matches exactly to member_id in the members lookup. I don't know why it's called 'processor' on that one.
- Preview Caption
     - created and displayed in the client, not stored in the db
