### ISSUE TITLE
Add Map to site-details

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#229]
- [x] expand map on button click "Show Site Map" 
- [x] button is in first expandable section on site-details page
- [x] spiderfy map items on load

**Comment by Abigail770** [comment]
Is this the Spiderify library you're thinking of? 
https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet

**Comment by lprivette** [comment]
Yes that is the one we've used in the past. If you're working on this now, do you think it makes sense to do the spiderfy thing? or is it overkill? 

I'm wondering if it's worth it honestly. Could just do buffers around the icons or something similar.
