### ISSUE TITLE
Remove Filter Headers

### ISSUE THREAD

**Issue by chaqazarad** [USGS-WiM/stnweb2#238]
- Remove expandable/collapsible headers
- Seems like we lost the ability to use the Event selector as a dropdown, now only input/typeahead
- Consider changing Clear Filters from a button to a link, really helps quickly differentiate between the two actions also remove the clear filters icon I think it might be more confusing than helpful

**Comment by Abigail770** [comment]
@chaqazarad for the first bullet, did you mean removing the collapsible headers here? (it's been so long since we talked about this, I forget what we decided).
![image](https://user-images.githubusercontent.com/54085652/167493573-22b06a67-8c19-4885-82d0-d14efd9f86fc.png)

**Comment by lprivette** [comment]
I think it was meant for the first section only which looks like was already done? We can always open another ticket down the road.
