### ISSUE TITLE
Remove AWS WMA STNWebTest EC2 instance from the STOP txt file

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#252]
We will be doing active development with editing and delete and need to use the test services.

I know we're doing the STOP EC2 instances via lamba with the instances listed in a txt file on the Main AWS account. I don't have the permissions to view lambda or s3 pages on WMA AWS account so I'm not sure how it's getting done there.

**Comment by ChadFanguy-usgs** [comment]
Removed STNWebTest from the txt file in wma-lambda for the lambda function.
