### ISSUE TITLE
Add Scale Bar and measure tool to Map

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/stnweb2#26]
Enhancement request from cooperator:
- [ ] Scale Bar
- [ ] Measure tool

**Comment by lprivette** [comment]
They want English units, not metric

**Comment by 09Kathy** [comment]
It already has this - should I keep what's there and just delete the metric units?
![image](https://user-images.githubusercontent.com/46943254/98571556-41c95480-227a-11eb-82fa-272474faef98.png)

**Comment by lprivette** [comment]
ah nice! let's leave both.

**Comment by HansVraga** [comment]
wait, is there also ameasure tool?
