### ISSUE TITLE
Add ability to Edit Site information

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#263]
- [x] Admins, Managers, and Fields should each be able to edit a site
- [x] Put an Edit Button and a disabled Delete Button (doesn't have to function for this ticket) see image below
          - I'd like to indicate to the Fields and Managers that sites can be deleted and that they should reach out to an admin if they need one deleted. So thinking we leave it disabled and add an info button with tooltip.
- [x] Clicking the Edit button opens a dialog with all the fields in a form. 
- [ ] User must click a 'confirm' acknowledgement after clicking "save" or "delete". 

-  ~~Option 1: Add an edit icon next to field. on clicking it the field would become an input and editable. clicking outside would save it and issue the PUT request.~~

option 2:
![image](https://user-images.githubusercontent.com/23640741/141205971-aa12a396-0930-47b6-8f2c-e7197603a85d.png)

**Comment by Abigail770** [comment]
I like the second option better because with the first option I could see someone accidentally changing a field and then having it save to the database.  I think having a separate "Editing Mode" and a Save Edits button would prompt people to go back through and check their edits.

**Comment by chaqazarad** [comment]
I also would advocate for option 2. Can show edit and delete buttons as disabled. Not sure if we would want to prompt users to check their edits, but maybe. We would atleast want to add a confirmation before saving edits/deleting.

**Comment by lprivette** [comment]
Very good points! I'll update the ticket and we'll go with option 2

**Comment by Abigail770** [comment]
I have a few more questions now that I've been working on the site edit form:
1. In the current STNWeb, the form has Location Info and Housing Info expansion panels.  It seems like we should keep things in the new form arranged the same way we have it on the site details page, with a Location Info and Additional Info panels.  

I'm wondering if we need to make any changes to the way things are arranged on the site details page.  There is a lot of info under the Location panel that I'm not sure is actually location info, for example landowner contact, network type/name, etc.

![image](https://user-images.githubusercontent.com/54085652/142658946-5692444c-d377-4fd1-84f7-f5e64669c1ab.png)
![image](https://user-images.githubusercontent.com/54085652/142659042-179a507d-d3ce-4b9d-add7-55fa620c0a48.png)
2. Current STNWeb has separate Save buttons for files and site info.  Should we keep it that way and submit them separately, or use a single Save button for both at the bottom of the dialog window?  To me it seems like it would make sense to at least have the Cancel button outside the expansion panels.
3. Current STNWeb has a tooltip next to the county in the form that says to use the Verify Location to populate the county.  Where is Verify Location?  I'm not seeing it anywhere in the site edit modal.  Should there be info about nearby sites here too?

**Comment by lprivette** [comment]
Discussed in slack:
1. https://github.com/USGS-WiM/stnweb2/issues/285
2. only editable in the respective tab/edit dialog, not in the aggregate Files tab
3. I think that tooltip shouldn't be there when editing and existing site. The Verify Location only happens when creating a new site. 
4
