### ISSUE TITLE
Add ability to add sensor files

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#271]
- [x] Add 'add file' button under the "Sensor File Information" section

**Comment by Abigail770** [comment]
Should you be able to add Link files for sensors, hwms and site files?

In the old STNweb test when I try to add a Link file for site and hwms, I can add one but when I open it to edit it afterwards there's an error: `exception: file item not found`.  (I think maybe `path: <link>` needs to be submitted with the request body, that's how it works for NWIS files anyway).

When I try to add a Link file for a sensor, I'm not able to add it.  A validation popup gives me a message that I need to upload a file.  If we don't actually need a file type link for sensors, I can remove the option from the dropdown in stnweb2.

**Comment by lprivette** [comment]
![image](https://user-images.githubusercontent.com/23640741/177603827-6457ac56-7248-425f-8224-c1f755a87d24.png)

Will hide option in sites file type too
