### ISSUE TITLE
Use USGS Search API for JS (TX API) for Geosearch

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/stnweb2#28]

**Comment by 09Kathy** [comment]
The USGS TX Search API requires jQuery, which, from what I've read ideally shouldn't be used with Angular. Should I install it anyways or look for an alternative search option?

**Comment by lprivette** [comment]
That is correct. Since we're already using `esri-leaflet` lets go with their geocoder instead of the USGS Search API

**Comment by lprivette** [comment]
Hans reaching out to Texas to see if there's an interest in removing the jQuery dependency.

**Comment by 09Kathy** [comment]
@lprivette , should I wait to see if we're going to replace it with the Texas one down the road, or keep at it with esri-leaflet? I was working on it this morning and it worked... but only after compiling the code twice (as to why, I do not understand).

**Comment by lprivette** [comment]
No, let's move forward with the esri-leaflet. It could take some time before a change to the texas search gets anywhere.

What do you mean compiling it twice? what command were you running?

**Comment by 09Kathy** [comment]
I run `ng serve` and it gives me an error about not being able to find `geosearch()` and then I change anything anywhere in the code (could even be adding a comment in a different file), press save, and then everything works perfectly.

**Comment by 09Kathy** [comment]
Is esri-leaflet better than the leaflet geosearch due to better address matching?

**Comment by lprivette** [comment]
not necessarily. It's more that I'd prefer to try to work within the third party libraries we're using, and avoid adding more random-ish ones. Repos owned by a company 'ESRI' are generally more reliable. An individual github user can make a wonderful plugin, but can also transfer ownership of the repo to whoever, whenever. That person can then add malicious code, and if your app is set to update a version, you'd bring that onto your own machine and application. Doesn't happen often, but did happen with a small package STNWeb used use.

is this the link for the leaflet one https://github.com/perliedman/leaflet-control-geocoder?

**Comment by 09Kathy** [comment]
Yeah, that makes sense. This is the link to the one I originally used: https://github.com/smeijer/leaflet-geosearch

The esri-leaflet one works well after it loads too, I just can't figure out why it always takes two tries to compile.

**Comment by lprivette** [comment]
yeah that is odd. I'll check out the branch and see if anything stands out to me.
