### ISSUE TITLE
Remove tapedowns from sensor table

### ISSUE THREAD

**Issue by Abigail770** [USGS-WiM/stnweb2#280]
tapedowns will still be accessible via the edit dialog. Laura stated the tapedowns are more of a tool for people entering the data but not really something they needed to see later.

commit where it was removed incase we have to backtrack on it: https://github.com/USGS-WiM/stnweb2/commit/8a93af52946c2f97e5c8442f3d9d11845df5bc45

**Comment by lprivette** [comment]
~!Crap I am blanking on why we decided to remove the tapedowns here. Do you remember @Abigail770 ? Were we incorporating them differently?~
