### ISSUE TITLE
Rearrange content on Site page

### ISSUE THREAD

**Issue by Abigail770** [USGS-WiM/stnweb2#285]
- Create a second column at the top of the page and add the address (address, city, county, state, zip) info there.
- All other fields should be in an Additional Information expansion panel below

**Comment by Abigail770** [comment]
We may want to put all required site fields at the top too.

Required fields in site edit form:
- site description
- lat
- lon
- horizontal datum
- horizontal collection method
- waterbody

**Comment by chaqazarad** [comment]
Make sure all columns on sites stack when the width gets too small. Easy thing to do to optimize for mobile.  In other words the secondary column should stack underneath the first column at certain widths.
