### ISSUE TITLE
Table Formatting

### ISSUE THREAD

**Issue by chaqazarad** [USGS-WiM/stnweb2#288]
- [x] On the front page open the "results" table by default.
- [x] Open the Map on a site record by default.
- [x] Open tables on the Files section by default. Better to show than hide content by default. We are defaulting number of records to 5, so length shouldn't be an issue. 
- [x] Instead of showing "No X Listed" for tables show a table with an empty row with that text. Its more helpful to see an empty table with column headers so you understand what information may be displayed.
![image](https://user-images.githubusercontent.com/85179214/143280622-e1083e67-f56b-466a-83b8-31161c4b4b0c.png)
- [x] Small thing but most of the time numeric columns in tables should always be right aligned. Left align headers and right align data fields. Not always the case, but I'm sure there are some columns that should be changed (some zero padding may be needed). A helpful illustration:
![image](https://user-images.githubusercontent.com/85179214/143283173-d9cf5bcd-de42-4e74-94dd-1db8ddd0c3ef.png)

**Comment by Abigail770** [comment]
@chaqazarad just wanted to clarify for the second point, did you mean have the map open by default on each Site page?

**Comment by chaqazarad** [comment]
Yes unless you guys disagree. It's just easier to miss things like that when they are closed by default.

**Comment by Abigail770** [comment]
Yup, that makes sense to me! One more question: should date and ID column data be right-aligned in the table too, or just numeric data?  I'm not sure what the standard is for that.

**Comment by chaqazarad** [comment]
In a table I would right align dates and keep IDs left aligned.
