### ISSUE TITLE
Changes to Reference Mark/Reference Datum tab

### ISSUE THREAD

**Issue by Abigail770** [USGS-WiM/stnweb2#294]
- [x] Add description field to initial table
- [x] Add active/destroyed/discontinued status
- [x] Clarify what date recovered and date established mean and change language if necessary

**Comment by Abigail770** [comment]
According to the tooltip in the edit modal, "Date recovered" is "the date the location was recently found in good condition".  Maybe date recovered could be changed to something like "Date checked"?

**Comment by lprivette** [comment]
Yes, or maybe "Date Last Checked" if they're updating that at all which I don't know if they do, so yeah "Date Checked" is good. 

For checkbox 2 there is an op_destroyed field which I don't believe is actually used in current stnweb, but we can start including it now, it is by default `0` (false). I think it will be good to just show it there and not add it to the 'add' or 'edit' modals yet. I think getting some users to look at it and say 'hmm, what is this'? will tell us whether or not this should be utilized or not.

**Comment by Abigail770** [comment]
Date Last Checked makes sense to me if it's used the way it's described in the tooltip.  Could be a question for the next user group meeting too.

I'll add in a column for the is_destroyed field.
