### ISSUE TITLE
Add outline to secondary buttons

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#308]
Secondary actions include:
- [x] Close
- [x] View details

**Comment by Abigail770** [comment]
Right now all buttons are secondary except Save (primary).  Should edit buttons be secondary?  Do we want additional styles for other actions like delete (e.g. red outline) and add (e.g. blue or green outline)?

**Comment by lprivette** [comment]
I would say edit is secondary keeping the blue outline, and then ADD green outline, and DELETE red outline.

I was thinking delete at least should be solid cause it's such a permanent action but I'm not liking the way this looks 
![image](https://user-images.githubusercontent.com/23640741/151880128-d67e96a2-87a5-455d-9e73-1d937fa24d3b.png)
