### ISSUE TITLE
Edit Site Modal Updates

### ISSUE THREAD

**Issue by chaqazarad** [USGS-WiM/stnweb2#311]
- [x] Add "Edit" to the modal title
- [x] Add Landowner button should not show when a landowner is already added or the button had been pressed
- [x] If landowner exists show a delete button > pressing delete should return to the default state (no fields showing just the add button)
- [x] Don't save the delete action until the user selects the primary Save button (unless this will cause extra complications/work)
- [x] Move the Save and Cancel actions into the fixed footer at the bottom
- [x] Change Save button to primary styling
- [x] Change Cancel to secondary styling
- [x] When a user hits Save the modal should close and a snackbar should show with messaging such as "[SiteName] was updated"
- [x] Cancel should abort and not save any changes made in the edit modal (the X at the top right should do the same)

Positioning of buttons in the fixed footer could be center or right aligned (or even left aligned). Do whatever is most consistent with the rest of the application. 

![image](https://user-images.githubusercontent.com/85179214/146962853-a78b56d9-1e2d-4188-9789-170666432ca4.png)
**
![image](https://user-images.githubusercontent.com/85179214/146962883-0b86b309-680d-4b23-a399-abec6b46dd51.png)
**

![image](https://user-images.githubusercontent.com/85179214/146962944-c0060498-5fdd-45bd-8de3-a8bed379f868.png)

**Comment by Abigail770** [comment]
There actually isn't a way to fully delete a landowner from a site in old STNweb after one has been fully submitted (if you add one to a site and then click save, then Edit Site again, the form can't be submitted again unless a landowner first name is populated).

Should we be able to delete an existing landowner?  Or should we just have a "Remove landowner" button only if there isn't an existing landowner - if the user clicks Add Landowner but hasn't Saved to the site yet (this would just reset the form and hide the fields)?

**Comment by lprivette** [comment]
Honestly I think this is likely a bug or simply something not accounted for in old stnweb by not handling the mandatory 'first name' field after adding a landowner initially. I'm not sure why, of all the fields, the first name is mandatory either. So I think we should allow the deletion of landowners

**Comment by Abigail770** [comment]
Yeah, only having the first name be mandatory seemed weird to me too.  I would think the last name would also be required then.

Okay, I'll add the ability to delete them then.  If there is an existing landowner then, and the user clicks Delete Landowner (clearing all form values), then clicks Add Landowner and fills out the form again (all before saving), should the existing landownercontact_id be used (put request), or should the original be deleted and a completely new landowner be added (delete + post)?

**Comment by chaqazarad** [comment]
Whatever the user sees when they hit Save should be what they get. Also that Save button is moving to the bottom of the modal right?

**Comment by lprivette** [comment]
I think it should be deleted in that case @Abigail770 and a new landowner be added, so 'delete + post'.

Yes, following that mock up it should be @chaqazarad

**Comment by Abigail770** [comment]
Yup, Save and Cancel will be fixed at the bottom right instead of in the Site Info expansion panel.  I was going to keep the file Save/Edit/Delete/Reupload separate still though
