### ISSUE TITLE
Manage Users - Review

### ISSUE THREAD

**Issue by chaqazarad** [USGS-WiM/stnweb2#316]
![image](https://user-images.githubusercontent.com/85179214/147770615-23c4a9cf-0273-4229-9817-f3dc94df8de2.png)

- [x] Consider moving "Find User" in front of the filters and/or adding a page title "Manage Users" whatever works best
- [x] First 4 columns (presumably all columns) are sorting by uppercase alpha then lowercase alpha I think we just want alpha non case sensitive
- [ ] last 2 columns are not sorting. Is it because there are no lowercase values? 
- [x] capitalize the n in "Add new User" button

![image](https://user-images.githubusercontent.com/85179214/147770848-f4abd592-4431-4702-b17e-a733dc7e86ef.png)

- [x] Remove the "a" from "Add a New User"
- [x] Change "Enter your email" to "Email"
- [ ] You can type an agency. Will it create an agency when you add a user then? What are the implications, if any
- [x] add a space in Fullname in "Emergency Contact Fullname"
- [x] Remove the help icon from the password field, cant click on it and its just confusing
- [x] The save or primary action should be text instead of an icon (or text in addition to the icon) something like "Save" or "Add User"

**Comment by lprivette** [comment]
Thanks Daniel! I opened issues for the ones I did not address here:

- agency issue: https://github.com/USGS-WiM/stnweb2/issues/317 users need to select one, entered text should not be valid
- sorting not working issue: https://github.com/USGS-WiM/stnweb2/issues/318
- sorting case sensitive issue: https://github.com/USGS-WiM/stnweb2/issues/319
