### ISSUE TITLE
re-work selecting an Event to make it easier/faster (list is getting long)

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#33]
> STN and FEV - list of events is getting large. separate lists or areas for types of flooding. for example: tropical or coastal events and inland (or flood or better name) events

https://docs.google.com/spreadsheets/d/1nTcXmTEH9wexDHJ3AdgWNJnDZfO9EeTa9w6Kedp_HRc/edit#gid=2020526334

Need to brainstorm on this one. We could have a typing selector (as it is currently done in FEV, but not in STN Web). And/or we could display the 5 most recent events and then have a selector for event type and list alphabetically.

**Comment by 09Kathy** [comment]
Was this addressed in #106 ?

**Comment by lprivette** [comment]
The type-ahead is new and def contributes to making it faster. We'll close it and the user group can let us know if they want more than this.
