### ISSUE TITLE
Add ability to view Peak details

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#343]
Should open in a dialog consistent with the other tabs

**Comment by Abigail770** [comment]
In the old STN, clicking on a peak brings up a dialog with edit ability for the peaks - it doesn't show peak details and then have a separate edit button like the sensors, hwms and reference datum dialogs.  

I think it makes sense to have a details dialog and then have a separate edit button for peaks, but wasn't sure if there was a reason why peaks were displayed differently.  Or maybe there is a way to view peak details in the current STN that I'm not seeing.
