### ISSUE TITLE
Add ability to select an event from site page

### ISSUE THREAD

**Issue by Abigail770** [USGS-WiM/stnweb2#380]
Assuming we still want the ability to select an event on the site page in the new interface - if not (or if we discussed and I don't remember), feel free to close this.

**Comment by lprivette** [comment]
I feel like we did discuss and decided that we'd display the event name if one were selected but would return the users to the map page for changing events. @chaqazarad you have any thoughts or remembrances on this?

**Comment by lprivette** [comment]
I asked athena how often she changes event from the site page. Going to ask on the stn user group call today to for hopefully someone's opinion with field experience.
![image](https://user-images.githubusercontent.com/23640741/168105573-c112cb77-cc08-419d-b5cc-97aaa46f863f.png)

**Comment by Abigail770** [comment]
Asked the STNweb user group on 5/12 and determined that they didn't use the event selector on the site much.  But that a Clear Event button might be helpful to add to the site page (#383)
