### ISSUE TITLE
View Modal Data Field Display Issues

### ISSUE THREAD

**Issue by chaqazarad** [USGS-WiM/stnweb2#404]
Several data fields are not populating or display incorrectly in the view modal. 

HWM
- [x] Event - Not populating
- [x] Vertical Datum - Not populating
- [x] Vertical Collection Method - Not populating
- [x] Survey Uncertainty - Will only save as ft. cannot save as cm. Also units don't show in the view modal.

Reference Datum
- [x] Uncertainty - Has three stacked dashes to the right of it?

Deploy Sensor
- [x] Preview Time in UTC - Not populating
- [x] In Feet Above  - Not populating
- [x] Interval - Only saves and displays in seconds. Can't save/display in minutes.
- [x] Timezone - Only save and displays UTC. Cannot save/display another time zone (but time correctly updates).

Retrieve Sensor
- [x] In Feet Above - Not populating
- [x] Timezone - Only save and displays UTC. Cannot save/display another time zone (but time correctly updates).

**Comment by Abigail770** [comment]
For the fields that aren't populating - are they blank, or are they populated with '---'?  
They should be populated with '---' if there is no value for that field, but shouldn't be blank or undefined.

When you say "only saves and displays in" - is there an error or are the fields not populating correctly?
Units of time are converted to UTC before being stored in the database, so once a sensor is submitted, the view details modal should display the time as UTC.  Intervals in minutes are converted to seconds, and survey uncertainty in cm is converted to ft before being submitted.  Not sure if that's what you're seeing, but just wanted to clarify!

**Comment by chaqazarad** [comment]
What I was observing is fields show --- when there is actually data. 

I see so that's by design that you only ever want to see UTC or seconds or cm. The timezone field has an info bubble I missed which exaplains that. Might want to add info bubbles for those other cases.

**Comment by Abigail770** [comment]
Okay, good to know, that's definitely a bug! Thanks!  

I'll add info bubbles for fields with units that are converted before submitting.
