### ISSUE TITLE
Users must select an associated HWM when adding a new HWM File

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#414]
HWM Files should have a 'hwm_id' associated with them.

For adding a HWM file via the Files Tab, I suggest we add a dropdown to the top of the add modal where users select the HWM they want to associate the file with.

**Comment by Abigail770** [comment]
I think this has already been implemented:
![image](https://user-images.githubusercontent.com/54085652/173587596-36442c98-cafd-4c8a-a08a-f6980dafaa9d.png)
