### ISSUE TITLE
Set up sites service and getEventSites function

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#60]
We'll be using this endpoint to display points on the map by event. https://stn.wim.usgs.gov/STNServices/Documentation/Site/EventSites

- [x] Add `sites` service
- [x] create `getEventSites` function inside `sites` service

**Comment by esmyers** [comment]
I have this set up, but am sort of poking through how to make a unit test for it now. Will take a bit more this afternoon to see if I can figure anything out, then probably just go ahead and commit on Monday to keep things moving.
