### ISSUE TITLE
Set up services for map filter type fields

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#71]
- [x] NetworkNames https://stn.wim.usgs.gov/STNServices/NetworkNames.json
- [x] States https://stn.wim.usgs.gov/STNServices/States.json
- [x] SensorTypes https://stn.wim.usgs.gov/STNServices/SensorTypes.json

**Comment by 09Kathy** [comment]
@lprivette , which of these should be single option vs multiselect?

**Comment by lprivette** [comment]
network selections (need to allow multiple network selection)
 States (allow multiple selection)
 Sensor Types (dropdown, 1 select)

(sorry was in issue https://github.com/USGS-WiM/stnweb2/issues/70)
