### ISSUE TITLE
Create Layer for all STN Sites

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#95]
This is currently a non-operational layer in legacy STNWeb. Laura and Athena have both stated it would be useful. 

This layer might effect the site's performance because of it's size, but lets give it a try.

- [x] In sites services create function to getAllSites
- [x] create "STN SITES ALL" layer

If it works well go ahead and submit PR, if not just report back in this ticket.

**Comment by 09Kathy** [comment]
@lprivette , I haven't found an efficient way to add the full layer to the map without making everything super slow. Right now, I have it set at min zoom 12 - even that is still a little slow. However, if the point of this layer is to see the nationwide distribution of sites, that is not helpful. If they want it to see if there are sites in a specific area, maybe it's worth keeping. What do you think?
