### ISSUE TITLE
Set up map filters

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/stnweb2#96]
Type field services were setup with this issue: https://github.com/USGS-WiM/stnweb2/issues/71

Filters will work almost the same as the legacy STNWeb. The one difference is that they will be able to select multiple Networks as opposed to only one.

~Users must select an event~ Users can filter by any of the following:
- Event
- States (multiple)
- Sensor Type (one)
- Network Names (multiple)
- HWMs Surveyed (one, this one is currently a checkbox but may need to switch to a toggle. Just need to ensure they can only filter by one not both)
- Checkboxes (can select multiple)
     - HWM Only Sites
     - Sensor Only Sites
     - Surveyed RP Only Sites
     - Pre-Deployed Bracket Sites Only
     - RDG Only Sites
     - Has OP Defined

Once they've completed the section with the filters they want, users will click a "Filter Sites" button and the map will update. There will also be a 'Clear Filters' button that will clear the selections incase they want to start from scratch.

Some example searches:
1. A user wants to view all sites in North and South Carolina. The user selects both states in the 'States' selector, clicks the 'Filter Sites' button, and the map updates with sites in those two states.
2. A user wants to view all Surveyed HWMs in the South Atlantic network for all events. The user selects the South Atlantic network from the Network selector, checks the 'Surveyed' box, clicks the 'Filter Sites' button, and the map updates.
3. A user wants to view sites with RDG for the Hurricane Dorian event. The user selects hurricane Dorian in the 'Event' selector, checks the box for 'RDG Only Sites', clicks the 'Filter Sites' button, and the map updates

The 'Filtered Sites' endpoint is the one you'll want to use 
https://stn.wim.usgs.gov/STNServices/Documentation/Site/FilteredSites

**Comment by BlakeDraper** [comment]
@lprivette One of the key design features of the current STNWeb is the "Session Event' construct, wherein user sets the context of the Event they wish to work with, setting the event name at the top, but more importantly setting that as the context for the site details, since Sites are used across many events. 

Are we abandoning that construct for STNWeb2? And if so, has there been thought around how to bring context to the deets for a specific event once a user clicks to visit site details?

**Comment by lprivette** [comment]
Another key feature is to be able to filter without selecting an event. Athena will frequently use non-event specific site filtering on storm calls for example, to show coverage over network(s)s or state(s).

So no not abandoning, it will filter the same as it does in current STNWeb, users can either select an event and filter those results, or not select an event and filter based on all sites.

My thoughts for the site details is that it would reflect the filter ran (with or without an event selected). With the table loading 20 or so at a time as some of the results can be massvie.

**Comment by BlakeDraper** [comment]
Ok, makes sense- but def downplaying the Event primacy in the filtering and general UX - as it is, it kind of maintains the Event selection as a top level thing visually. Sounds like the redesign will de-emphasize the Event a bit and make it more of just one of the many filters?

**Comment by lprivette** [comment]
Yes, essentially making it equal to the other filters, but still listed first in the Map selections, which I'd argue makes it slightly more prominent than the other filters. We could also call it out more in that section (as opposed to it's own dialog in the navbar) if we do feel the need to make it more event centric. That area could def use a css expert.

**Comment by esmyers** [comment]
@lprivette I'm looking here to find an option documenting the pre-deployed bracket sites. https://stn.wim.usgs.gov/STNServices/Documentation/Site/FilteredSites

It seems like stnweb test is using the parameter HousingTypeOne=1 in the URL, and it seems to be working in the STN services above.  Can you confirm that HousingTypeOne=1 is the correct parameter when the PRE-DEPLOYED BRACKET SITES ONLY box is checked?

**Comment by lprivette** [comment]
Confirmed, `housing_type_id` = 1, is "Pre-Deployed Bracket" and that's the correct parameter for that checkbox

You can verify here too: https://stn.wim.usgs.gov/STNServices/Documentation/HousingType/AllHousingTypes

I see I need to update the documentation with that parameter lol
